# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schain.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cschain.proto\"\xcd\x04\n\nSchainMain\x12\"\n\x06schain\x18\x01 \x01(\x0b\x32\x12.SchainMain.Schain\x1a\x83\x01\n\tAnon_cert\x12\x16\n\x0e\x64\x65vice_pub_key\x18\x01 \x01(\x0c\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x17\n\x0fissuer_cert_url\x18\x03 \x01(\t\x12\x12\n\nexpiration\x18\x04 \x01(\x04\x12\x1e\n\x16manufacturer_signature\x18\x05 \x01(\x0c\x1a\xef\x01\n\x05Nodes\x12\x11\n\x04hmac\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x1a\n\rprivacy_block\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0b\n\x03\x61si\x18\x03 \x01(\t\x12\x15\n\x08next_hop\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x0b\n\x03sid\x18\x05 \x01(\t\x12\x10\n\x03rid\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\n\n\x02hp\x18\x07 \x01(\r\x12\x1b\n\x13potential_verifiers\x18\x08 \x03(\t\x12\x1b\n\x13recipient_verifiers\x18\t \x03(\tB\x07\n\x05_hmacB\x10\n\x0e_privacy_blockB\x0b\n\t_next_hopB\x06\n\x04_rid\x1a\xa2\x01\n\x06Schain\x12\x10\n\x08\x63omplete\x18\x01 \x01(\r\x12\x0b\n\x03ver\x18\x02 \x01(\t\x12\x17\n\x0ftoken_plaintext\x18\x03 \x01(\t\x12\x14\n\x0ctoken_signed\x18\x04 \x01(\x0c\x12(\n\tanon_cert\x18\x05 \x01(\x0b\x32\x15.SchainMain.Anon_cert\x12 \n\x05nodes\x18\x06 \x03(\x0b\x32\x11.SchainMain.Nodesb\x06proto3'
)




_SCHAINMAIN_ANON_CERT = _descriptor.Descriptor(
  name='Anon_cert',
  full_name='SchainMain.Anon_cert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_pub_key', full_name='SchainMain.Anon_cert.device_pub_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='SchainMain.Anon_cert.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issuer_cert_url', full_name='SchainMain.Anon_cert.issuer_cert_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='SchainMain.Anon_cert.expiration', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer_signature', full_name='SchainMain.Anon_cert.manufacturer_signature', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=199,
)

_SCHAINMAIN_NODES = _descriptor.Descriptor(
  name='Nodes',
  full_name='SchainMain.Nodes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hmac', full_name='SchainMain.Nodes.hmac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='privacy_block', full_name='SchainMain.Nodes.privacy_block', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asi', full_name='SchainMain.Nodes.asi', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_hop', full_name='SchainMain.Nodes.next_hop', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sid', full_name='SchainMain.Nodes.sid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rid', full_name='SchainMain.Nodes.rid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hp', full_name='SchainMain.Nodes.hp', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='potential_verifiers', full_name='SchainMain.Nodes.potential_verifiers', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipient_verifiers', full_name='SchainMain.Nodes.recipient_verifiers', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_hmac', full_name='SchainMain.Nodes._hmac',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_privacy_block', full_name='SchainMain.Nodes._privacy_block',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_next_hop', full_name='SchainMain.Nodes._next_hop',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_rid', full_name='SchainMain.Nodes._rid',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=202,
  serialized_end=441,
)

_SCHAINMAIN_SCHAIN = _descriptor.Descriptor(
  name='Schain',
  full_name='SchainMain.Schain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='complete', full_name='SchainMain.Schain.complete', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ver', full_name='SchainMain.Schain.ver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_plaintext', full_name='SchainMain.Schain.token_plaintext', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_signed', full_name='SchainMain.Schain.token_signed', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anon_cert', full_name='SchainMain.Schain.anon_cert', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='SchainMain.Schain.nodes', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=606,
)

_SCHAINMAIN = _descriptor.Descriptor(
  name='SchainMain',
  full_name='SchainMain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='schain', full_name='SchainMain.schain', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SCHAINMAIN_ANON_CERT, _SCHAINMAIN_NODES, _SCHAINMAIN_SCHAIN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=606,
)

_SCHAINMAIN_ANON_CERT.containing_type = _SCHAINMAIN
_SCHAINMAIN_NODES.containing_type = _SCHAINMAIN
_SCHAINMAIN_NODES.oneofs_by_name['_hmac'].fields.append(
  _SCHAINMAIN_NODES.fields_by_name['hmac'])
_SCHAINMAIN_NODES.fields_by_name['hmac'].containing_oneof = _SCHAINMAIN_NODES.oneofs_by_name['_hmac']
_SCHAINMAIN_NODES.oneofs_by_name['_privacy_block'].fields.append(
  _SCHAINMAIN_NODES.fields_by_name['privacy_block'])
_SCHAINMAIN_NODES.fields_by_name['privacy_block'].containing_oneof = _SCHAINMAIN_NODES.oneofs_by_name['_privacy_block']
_SCHAINMAIN_NODES.oneofs_by_name['_next_hop'].fields.append(
  _SCHAINMAIN_NODES.fields_by_name['next_hop'])
_SCHAINMAIN_NODES.fields_by_name['next_hop'].containing_oneof = _SCHAINMAIN_NODES.oneofs_by_name['_next_hop']
_SCHAINMAIN_NODES.oneofs_by_name['_rid'].fields.append(
  _SCHAINMAIN_NODES.fields_by_name['rid'])
_SCHAINMAIN_NODES.fields_by_name['rid'].containing_oneof = _SCHAINMAIN_NODES.oneofs_by_name['_rid']
_SCHAINMAIN_SCHAIN.fields_by_name['anon_cert'].message_type = _SCHAINMAIN_ANON_CERT
_SCHAINMAIN_SCHAIN.fields_by_name['nodes'].message_type = _SCHAINMAIN_NODES
_SCHAINMAIN_SCHAIN.containing_type = _SCHAINMAIN
_SCHAINMAIN.fields_by_name['schain'].message_type = _SCHAINMAIN_SCHAIN
DESCRIPTOR.message_types_by_name['SchainMain'] = _SCHAINMAIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchainMain = _reflection.GeneratedProtocolMessageType('SchainMain', (_message.Message,), {

  'Anon_cert' : _reflection.GeneratedProtocolMessageType('Anon_cert', (_message.Message,), {
    'DESCRIPTOR' : _SCHAINMAIN_ANON_CERT,
    '__module__' : 'schain_pb2'
    # @@protoc_insertion_point(class_scope:SchainMain.Anon_cert)
    })
  ,

  'Nodes' : _reflection.GeneratedProtocolMessageType('Nodes', (_message.Message,), {
    'DESCRIPTOR' : _SCHAINMAIN_NODES,
    '__module__' : 'schain_pb2'
    # @@protoc_insertion_point(class_scope:SchainMain.Nodes)
    })
  ,

  'Schain' : _reflection.GeneratedProtocolMessageType('Schain', (_message.Message,), {
    'DESCRIPTOR' : _SCHAINMAIN_SCHAIN,
    '__module__' : 'schain_pb2'
    # @@protoc_insertion_point(class_scope:SchainMain.Schain)
    })
  ,
  'DESCRIPTOR' : _SCHAINMAIN,
  '__module__' : 'schain_pb2'
  # @@protoc_insertion_point(class_scope:SchainMain)
  })
_sym_db.RegisterMessage(SchainMain)
_sym_db.RegisterMessage(SchainMain.Anon_cert)
_sym_db.RegisterMessage(SchainMain.Nodes)
_sym_db.RegisterMessage(SchainMain.Schain)


# @@protoc_insertion_point(module_scope)
